# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: apiclient
generate:
  models: true
  client: true
output: apiclient.gen.go
output-options:
  nullable-type: true
