// Code generated by tools/gen-version from internal/apiclient/openapi.yaml. DO NOT EDIT.

package skycloak

// DefaultAPIVersion is the API version this provider build is generated and
// tested against. An unpinned client sends it in the required API-Version
// header on every request.
const DefaultAPIVersion = "2026-06-01.beta"
