// Command gen-version extracts the first value of the Versions enum from the
// committed OpenAPI spec and writes it as the skycloak package's
// DefaultAPIVersion constant. The API requires the API-Version header on every
// request; the generated constant keeps the unpinned default in lockstep with
// the spec the client is generated from.
package main

import (
	"fmt"
	"os"
	"regexp"
)

func main() {
	spec, err := os.ReadFile("openapi.yaml")
	if err != nil {
		fatal(err)
	}
	// Match the Versions schema's first enum entry:
	//   Versions:
	//     type: string
	//     enum:
	//       - 2026-06-01.beta
	re := regexp.MustCompile(`(?s)Versions:\s*\n\s*type: string\s*\n\s*enum:\s*\n\s*- ([0-9]{4}-[0-9]{2}-[0-9]{2}[A-Za-z0-9.\-]*)`)
	m := re.FindSubmatch(spec)
	if m == nil {
		fatal(fmt.Errorf("could not find the Versions enum in openapi.yaml"))
	}
	out := fmt.Sprintf(`// Code generated by tools/gen-version from internal/apiclient/openapi.yaml. DO NOT EDIT.

package skycloak

// DefaultAPIVersion is the API version this provider build is generated and
// tested against. An unpinned client sends it in the required API-Version
// header on every request.
const DefaultAPIVersion = %q
`, string(m[1]))
	if err := os.WriteFile("../skycloak/version.gen.go", []byte(out), 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen-version:", err)
	os.Exit(1)
}
